# yaml-language-server: $schema=https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/main/src/main/resources/jsonSchemas/antoraPlaybookSchema.json

runtime:
  cache_dir: ./.cache/antora

site:
  title: Requirements Tool
  url: https://github.com/Luftfartsverket/reqstool-docs
  start_page: reqstool-docs::index.adoc

content:
  sources:
    - url: https://github.com/Luftfartsverket/reqstool-client
      branches: HEAD
      start_path: docs
    - url: https://github.com/Luftfartsverket/reqstool-demo
      branches: HEAD
      start_path: docs
    - url: https://github.com/Luftfartsverket/reqstool-java-annotations
      branches: HEAD
      start_path: docs
    - url: https://github.com/Luftfartsverket/reqstool-java-maven-plugin
      branches: HEAD
      start_path: docs
    - url: https://github.com/Luftfartsverket/reqstool-python-decorators
      branches: HEAD
      start_path: docs
    - url: https://github.com/Luftfartsverket/reqstool-python-poetry-plugin
      branches: HEAD
      start_path: docs
    - url: https://github.com/Luftfartsverket/reqstool-python-hatch-plugin 
      branches: HEAD
      start_path: docs

asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
    kroki-server-url: https://kroki.io
    kroki-fetch-diagram: true
    allow-uri-read: true
    sectnumlevels: 4
    toclevels: 3
  extensions:
    - asciidoctor-kroki

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
